farmdrop/apps/saleor/dashboard/discount/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sale/$', views.sale_list, name='sale-list'),
    url(r'sale/(?P<pk>[0-9]+)/$', views.sale_edit, name='sale-update'),
    url(r'sale/add/$', views.sale_edit, name='sale-add'),
    url(r'sale/(?P<pk>[0-9]+)/delete/$', views.sale_delete, name='sale-delete'),

    url(r'voucher/$', views.voucher_list, name='voucher-list'),
    url(r'voucher/(?P<pk>[0-9]+)/$', views.voucher_edit, name='voucher-update'),
    url(r'voucher/add/$', views.voucher_edit, name='voucher-add'),
    url(r'voucher/(?P<pk>[0-9]+)/delete/$', views.voucher_delete, name='voucher-delete'),
]

farmdrop/apps/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

farmdrop/apps/saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import api
from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^add/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/',
        views.variants_bulk_delete, name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$',
        views.stock_edit, name='product-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/',
        views.stock_bulk_delete, name='stock-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$',
        api.reorder_product_images, name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$',
        api.upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
]

farmdrop/apps/saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .payments.urls import urlpatterns as payments_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .shipping.urls import urlpatterns as shipping_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^payments/', include(payments_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^shipping/', include(shipping_urls)),
]

farmdrop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from saleor.cart.urls import urlpatterns as cart_urls
from saleor.checkout.urls import urlpatterns as checkout_urls
from saleor.core.sitemaps import sitemaps
from saleor.core.urls import urlpatterns as core_urls
from saleor.order.urls import urlpatterns as order_urls
from saleor.product.urls import urlpatterns as product_urls
from saleor.registration.urls import urlpatterns as registration_urls
from saleor.userprofile.urls import urlpatterns as userprofile_urls
from saleor.dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url(r'^robots.txt', include('robots.urls')),
]

# This is only needed when using runserver.
if settings.DEBUG:
    import debug_toolbar
    from django.views.static import  serve
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^__debug__/', include(debug_toolbar.urls))
        ]

farmdrop/apps/saleor/discount/models.py
from __future__ import unicode_literals
from datetime import date
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.db.models import F
from django.utils.translation import pgettext, pgettext_lazy
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django_countries import countries
from django_prices.models import PriceField
from django_prices.templatetags.prices_i18n import net
from prices import FixedDiscount, percentage_discount, Price

from ..cart.utils import (
    get_product_variants_and_prices, get_category_variants_and_prices)


class NotApplicable(ValueError):
    pass


class VoucherQueryset(models.QuerySet):

    def active(self):
        today = date.today()
        queryset = self.filter(
            models.Q(usage_limit__isnull=True) | models.Q(used__lt=models.F('usage_limit')))
        queryset = queryset.filter(
            models.Q(end_date__isnull=True) | models.Q(end_date__gte=today))
        queryset = queryset.filter(start_date__lte=today)
        return queryset

    def increase_usage(self, voucher):
        voucher.used = F('used') + 1
        voucher.save(update_fields=['used'])

    def decrease_usage(self, voucher):
        voucher.used = F('used') - 1
        voucher.save(update_fields=['used'])


@python_2_unicode_compatible
class Voucher(models.Model):

    APPLY_TO_ONE_PRODUCT = 'one'
    APPLY_TO_ALL_PRODUCTS = 'all'

    APPLY_TO_PRODUCT_CHOICES = (
        (APPLY_TO_ONE_PRODUCT,
         pgettext_lazy('voucher', 'Apply to a single item')),
        (APPLY_TO_ALL_PRODUCTS,
         pgettext_lazy('voucher', 'Apply to all matching products')))

    DISCOUNT_VALUE_FIXED = 'fixed'
    DISCOUNT_VALUE_PERCENTAGE = 'percentage'

    DISCOUNT_VALUE_TYPE_CHOICES = (
        (DISCOUNT_VALUE_FIXED,
         pgettext_lazy('voucher', settings.DEFAULT_CURRENCY)),
        (DISCOUNT_VALUE_PERCENTAGE, pgettext_lazy('voucher', '%')))

    PRODUCT_TYPE = 'product'
    CATEGORY_TYPE = 'category'
    SHIPPING_TYPE = 'shipping'
    VALUE_TYPE = 'value'

    TYPE_CHOICES = (
        (VALUE_TYPE, pgettext_lazy('voucher', 'All purchases')),
        (PRODUCT_TYPE, pgettext_lazy('voucher', 'One product')),
        (CATEGORY_TYPE, pgettext_lazy('voucherl', 'A category of products')),
        (SHIPPING_TYPE, pgettext_lazy('voucher', 'Shipping')))

    type = models.CharField(
        pgettext_lazy('voucher', 'discount for'), max_length=20,
        choices=TYPE_CHOICES, default=VALUE_TYPE)
    name = models.CharField(
        pgettext_lazy('voucher', 'name'), max_length=255, null=True,
        blank=True)
    code = models.CharField(
        pgettext_lazy('voucher', 'code'), max_length=12, unique=True,
        db_index=True)
    usage_limit = models.PositiveIntegerField(
        pgettext_lazy('voucher', 'usage limit'), null=True, blank=True)
    used = models.PositiveIntegerField(default=0, editable=False)
    start_date = models.DateField(
        pgettext_lazy('voucher', 'start date'), default=date.today)
    end_date = models.DateField(
        pgettext_lazy('voucher', 'end date'), null=True, blank=True)

    discount_value_type = models.CharField(
        pgettext_lazy('voucher', 'discount type'), max_length=10,
        choices=DISCOUNT_VALUE_TYPE_CHOICES, default=DISCOUNT_VALUE_FIXED)
    discount_value = models.DecimalField(
        pgettext_lazy('voucher', 'discount value'), max_digits=12,
        decimal_places=2)

    # not mandatory fields, usage depends on type
    product = models.ForeignKey('product.Product', blank=True, null=True)
    category = models.ForeignKey('product.Category', blank=True, null=True)
    apply_to = models.CharField(max_length=20, blank=True, null=True)
    limit = PriceField(max_digits=12, decimal_places=2, null=True,
                       blank=True, currency=settings.DEFAULT_CURRENCY)

    objects = VoucherQueryset.as_manager()

    @property
    def is_free(self):
        return (self.discount_value == Decimal(100) and
                self.discount_value_type == Voucher.DISCOUNT_VALUE_PERCENTAGE)

    def __str__(self):
        if self.name:
            return self.name
        discount = '%s%s' % (
            self.discount_value, self.get_discount_value_type_display())
        if self.type == Voucher.SHIPPING_TYPE:
            if self.is_free:
                return pgettext('voucher', 'Free shipping')
            else:
                return pgettext('voucher', '%(discount)s off shipping') % {
                    'discount': discount}
        if self.type == Voucher.PRODUCT_TYPE:
            return pgettext('voucher', '%(discount)s off %(product)s') % {
                'discount': discount, 'product': self.product}
        if self.type == Voucher.CATEGORY_TYPE:
            return pgettext('voucher', '%(discount)s off %(category)s') % {
                'discount': discount, 'category': self.category}
        return pgettext('voucher', '%(discount)s off') % {'discount': discount}

    def get_apply_to_display(self):
        if self.type == Voucher.SHIPPING_TYPE and self.apply_to:
            return countries.name(self.apply_to)
        if self.type == Voucher.SHIPPING_TYPE:
            return pgettext('voucher', 'Any country')
        if self.apply_to and self.type in {
                Voucher.PRODUCT_TYPE, Voucher.CATEGORY_TYPE}:
            choices = dict(self.APPLY_TO_PRODUCT_CHOICES)
            return choices[self.apply_to]

    def get_fixed_discount_for(self, amount):
        if self.discount_value_type == self.DISCOUNT_VALUE_FIXED:
            discount_price = Price(net=self.discount_value,
                                   currency=settings.DEFAULT_CURRENCY)
            discount = FixedDiscount(
                amount=discount_price, name=smart_text(self))
        elif self.discount_value_type == self.DISCOUNT_VALUE_PERCENTAGE:
            discount = percentage_discount(
                value=self.discount_value, name=smart_text(self))
            fixed_discount_value = amount - discount.apply(amount)
            discount = FixedDiscount(
                amount=fixed_discount_value, name=smart_text(self))
        else:
            raise NotImplementedError('Unknown discount value type')
        if discount.amount > amount:
            return FixedDiscount(amount, name=smart_text(self))
        else:
            return discount

    def get_discount_for_checkout(self, checkout):
        if self.type == Voucher.VALUE_TYPE:
            cart_total = checkout.cart.get_total()
            limit = self.limit if self.limit is not None else cart_total
            if cart_total < limit:
                msg = pgettext(
                    'voucher',
                    'This offer is only valid for orders over %(amount)s.')
                raise NotApplicable(msg % {'amount': net(limit)})
            return self.get_fixed_discount_for(cart_total)

        elif self.type == Voucher.SHIPPING_TYPE:
            if not checkout.is_shipping_required:
                msg = pgettext(
                    'voucher', 'Your order does not require shipping.')
                raise NotApplicable(msg)
            shipping_method = checkout.shipping_method
            if not shipping_method:
                msg = pgettext(
                    'voucher', 'Please select a shipping method first.')
                raise NotApplicable(msg)
            if (self.apply_to and
                    shipping_method.country_code != self.apply_to):
                msg = pgettext(
                    'voucher', 'This offer is only valid in %(country)s.')
                raise NotApplicable(msg % {
                    'country': self.get_apply_to_display()})
            if self.limit is not None and shipping_method.price > self.limit:
                msg = pgettext(
                    'voucher',
                    'This offer is only valid for shipping over %(amount)s.')
                raise NotApplicable(msg % {'amount': net(self.limit)})
            return self.get_fixed_discount_for(shipping_method.price)

        elif self.type in (Voucher.PRODUCT_TYPE, Voucher.CATEGORY_TYPE):
            if self.type == Voucher.PRODUCT_TYPE:
                prices = list(
                    (item[1] for item in get_product_variants_and_prices(
                        checkout.cart, self.product)))
            else:
                prices = list(
                    (item[1] for item in get_category_variants_and_prices(
                        checkout.cart, self.category)))
            if len(prices) == 0:
                msg = pgettext(
                    'voucher', 'This offer is only valid for selected items.')
                raise NotApplicable(msg)
            if self.apply_to == Voucher.APPLY_TO_ALL_PRODUCTS:
                discounts = (
                    self.get_fixed_discount_for(price) for price in prices)
                discount_total = sum(
                    (discount.amount for discount in discounts),
                    Price(0, currency=settings.DEFAULT_CURRENCY))
                return FixedDiscount(discount_total, smart_text(self))
            else:
                product_total = sum(
                    prices, Price(0, currency=settings.DEFAULT_CURRENCY))
                return self.get_fixed_discount_for(product_total)

        else:
            raise NotImplementedError('Unknown discount type')


@python_2_unicode_compatible
class Sale(models.Model):
    FIXED = 'fixed'
    PERCENTAGE = 'percentage'

    DISCOUNT_TYPE_CHOICES = (
        (FIXED, pgettext_lazy('discount_type', settings.DEFAULT_CURRENCY)),
        (PERCENTAGE, pgettext_lazy('discount_type', '%')))

    name = models.CharField(max_length=255)
    type = models.CharField(max_length=10, choices=DISCOUNT_TYPE_CHOICES,
                            default=FIXED)
    value = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    products = models.ManyToManyField('product.Product', blank=True)

farmdrop/apps/saleor/dashboard/templates/dashboard/discount/sale_confirm_delete.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Delete sale" %} - {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:product-attributes' %}" class="breadcrumbs--ellipsed-item">{% trans "Discounts" %}</a></li>
        <li><span class="breadcrumbs--ellipsed-item"><i class="mdi-navigation-chevron-right"></i> {% trans "Delete sale" %}</span></li>
    </ul>
{% endblock %}

{% block content %}
    <p>{% trans "Are you sure you want to delete the following sale?" %}</p>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <ul class="collection">
                <li class="collection-item">
                    {{ sale }}
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col m6 l4 offset-m3 offset-l4 right-align">
                <a href="{% url 'dashboard:sale-list' %}" class="btn-flat"><i class="mdi-content-clear"></i> {% trans "Cancel" %}</a>
                <button type="submit" class="btn materialize-red"><i class="mdi-action-delete"></i> {% trans "Delete" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

farmdrop/apps/saleor/dashboard/templates/dashboard/discount/sale_form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}{% if sale.pk %}{{ sale }}{% else %}{% trans 'Add new sale' %}
{% endif %} - {% trans "Sales" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-sales{% endblock %}

{% block header_menu %}
    {% url "dashboard:sale-list" as url %}
    {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block header_extra %}
    {% if sale.pk %}
        <a class="dropdown-button" href="#" data-activates="sale-delete"
           data-constrainwidth="false">
            <i class="mdi-navigation-more-vert"></i>
        </a>
        <ul id="sale-delete" class="dropdown-content">
            <li>
                <a class="modal-trigger-custom" href="#base-modal"
                   data-href="{% url 'dashboard:sale-delete' pk=sale.pk %}">
                    {% trans "Remove sale" %}
                </a>
            </li>
        </ul>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:sale-list' %}"
               class="breadcrumbs--ellipsed-item">{% trans "Sales" %}</a></li>
        <li><span class="breadcrumbs--ellipsed-item">{% if sale.pk %}{{ sale }}{% else %}
            {% trans 'Add new sale' %}{% endif %}</span></li>
    </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" id="form-sales">
        <div class="row">
            <div class="col l8">
                <div class="row">
                    {% csrf_token %}
                    {{ form.name|materializecss }}
                    {{ form.value|materializecss:"s12 m8" }}
                    {{ form.type|materializecss:"s12 m4" }}
                    {{ form.products|materializecss }}
                    {{ form.categories|materializecss }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col l8 right-align">
                {% if sale.pk %}
                    <button type="submit" class="btn">{% trans "Update" %}</button>
                {% else %}
                    <button type="submit" class="btn">{% trans "Create" %}</button>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

farmdrop/apps/saleor/dashboard/templates/dashboard/discount/sale_list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load materializecss %}

{% block title %}{% trans "Sales" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-sales{% endblock %}

{% block header_extra %}
    <div class="fixed-action-btn">
        <a class="btn-fab btn-floating btn-large waves-effect waves-light teal"
            href="{% url 'dashboard:sale-add' %}" title="{% trans "Add sale" %}">
            <i class="mdi-content-add"></i>
        </a>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs">
        <li>{% trans "Sales" %}</li>
    </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block content %}
    {% if sales %}
        <div class="card">
            <div class="data-table-container">
                <table class="bordered hoverable responsive data-table">
                    <thead>
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Discount" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for sale in sales %}
                        <tr>
                            <td>
                                <a href="{% url 'dashboard:sale-update' pk=sale.pk %}">{{ sale }}</a>
                            </td>
                            <td>{{ sale.value }}{{ sale.get_type_display }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {% include "dashboard/includes/_pagination.html" %}
    {% else %}
        <p>{% trans "No sales found." %}</p>
    {% endif %}
{% endblock %}

farmdrop/apps/saleor/dashboard/templates/dashboard/discount/sale_modal_confirm_delete.html
{% load i18n %}

<form action="{% url "dashboard:sale-delete" pk=sale.pk %}" method="post">
    {% csrf_token %}
    <div class="modal-content">
        <h5>{% trans "Are you sure?" %}</h5>

        <p>
            {% blocktrans %}You are about to delete <strong>{{ sale }}</strong>.{% endblocktrans %}
        </p>
    </div>

    <div class="modal-footer">
        <button type="submit" class="modal-action btn-flat blue-text">{% trans "Delete" %}</button>
        <a href="#!" class="modal-action modal-close btn-flat blue-text">{% trans "Cancel" %}</a>
    </div>
</form>

farmdrop/apps/saleor/dashboard/templates/dashboard/discount/voucher_form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}{% if voucher.pk %}{{ voucher }}{% else %}{% trans 'Add new voucher' %}
{% endif %} - {% trans "Vouchers" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-vouchers{% endblock %}

{% block header_menu %}
    {% url "dashboard:voucher-list" as url %}
    {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block header_extra %}
    {% if voucher.pk %}
        <a class="dropdown-button" href="#" data-activates="voucher-delete"
           data-constrainwidth="false">
            <i class="mdi-navigation-more-vert"></i>
        </a>
        <ul id="voucher-delete" class="dropdown-content">
            <li>
                <a class="modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:voucher-delete' pk=voucher.pk %}">
                {% trans "Remove voucher" %}
                </a>
            </li>
        </ul>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:voucher-list' %}"
               class="breadcrumbs--ellipsed-item">{% trans "Vouchers" %}</a></li>
        <li><span class="breadcrumbs--ellipsed-item">{% if voucher.pk %}
            {{ voucher }}{% else %}{% trans 'Add new voucher' %}{% endif %}</span></li>
    </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" id="form-vouchers">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <blockquote>
                {% for non_field_error in form.non_field_errors %}
                    {{ non_field_error }}
                {% endfor %}
            </blockquote>
        {% endif %}
        <div class="row">
            <div class="col s12 l8">
                <div class="row">
                    {{ form.code|materializecss }}
                    {{ form.name|materializecss }}
                    {{ form.discount_value|materializecss:"s12 m8" }}
                    {{ form.discount_value_type|materializecss:"s12 m4" }}
                    {{ form.type|materializecss }}
                </div>
                {% for form_type, form in type_base_forms.items %}
                    <div class="row voucher-form" data-type="{{ form_type }}">
                        {% for field in form %}
                            {{ field|materializecss:"s12 m6" }}
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>

            <div class="col s12 l4">
                <div class="row">
                    {{ form.start_date|materializecss:"input-field s12" }}
                    {{ form.end_date|materializecss:"input-field s12" }}
                    {{ form.usage_limit|materializecss }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col l8 right-align">
                {% if voucher.pk %}
                    <button type="submit" class="btn">{% trans "Update" %}</button>
                {% else %}
                    <button type="submit" class="btn">{% trans "Create" %}</button>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

farmdrop/apps/saleor/dashboard/templates/dashboard/discount/voucher_modal_confirm_delete.html
{% load i18n %}

<form action="{% url "dashboard:voucher-delete" pk=voucher.pk %}" method="post">
    {% csrf_token %}
    <div class="modal-content">
        <h5>{% trans "Are you sure?" %}</h5>

        <p>
            {% blocktrans %}You are about to delete <strong>{{ voucher }}</strong>.{% endblocktrans %}
        </p>
    </div>

    <div class="modal-footer">
        <button type="submit" class="modal-action btn-flat blue-text">{% trans "Delete" %}</button>
        <a href="#!" class="modal-action modal-close btn-flat blue-text">{% trans "Cancel" %}</a>
    </div>
</form>